"""
Auto-generated Dagster pipeline for raw_nabca_table_1
Generated by Inspector Dom
Entity Type: INTERIM
"""

from dagster import (
    asset,
    AssetExecutionContext,
    MaterializeResult,
    MetadataValue,
    RetryPolicy,
)
from typing import Dict, Any, List, Optional
import logging
import traceback
import re
from datetime import datetime

# Configure logging
logger = logging.getLogger(__name__)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def parse_report_date_from_filename(filename: str) -> tuple:
    """
    Parse month and year from NABCA filename format.
    Expected format: XXX_XXX_MMYY.PDF (e.g., 631_9L_0125.PDF = January 2025)

    Returns:
        tuple: (month_name, year) or (None, None) if parsing fails
    """
    try:
        # Extract 4-digit pattern that looks like MMYY
        match = re.search(r'_(\d{4})\.', filename)
        if match:
            mmyy = match.group(1)
            month_num = int(mmyy[:2])
            year_suffix = int(mmyy[2:])

            # Convert to full year (20YY format)
            full_year = f"20{year_suffix:02d}"

            # Convert month number to name
            month_names = ['January', 'February', 'March', 'April', 'May', 'June',
                          'July', 'August', 'September', 'October', 'November', 'December']

            if 1 <= month_num <= 12:
                month_name = month_names[month_num - 1]
                return (month_name, full_year)

        # Fallback: Try to find any 4-digit pattern
        match = re.search(r'(\d{4})', filename)
        if match:
            mmyy = match.group(1)
            month_num = int(mmyy[:2])
            year_suffix = int(mmyy[2:])

            if 1 <= month_num <= 12:
                full_year = f"20{year_suffix:02d}"
                month_names = ['January', 'February', 'March', 'April', 'May', 'June',
                              'July', 'August', 'September', 'October', 'November', 'December']
                month_name = month_names[month_num - 1]
                return (month_name, full_year)

        return (None, None)
    except Exception as e:
        logger.warning(f"Failed to parse date from filename '{filename}': {e}")
        return (None, None)

# ============================================================================
# EXTRACTION ASSETS
# ============================================================================

@asset(
    name="extract_nabca_all_tables",
    description="Extract all 8 NABCA tables from PDFs using AWS Textract with table identification",
    compute_kind="extraction:textract:multi-entity",
    retry_policy=RetryPolicy(max_retries=3),
)
def extract_nabca_all_tables(context: AssetExecutionContext) -> Dict[str, Any]:
    """
    Multi-entity NABCA extraction: ONE Textract call → 8 database tables.

    Uses table identification patterns to route data to correct entities.
    Cost-efficient: 1 Textract call instead of 8 separate calls.
    """
    try:
        context.log.info("🚀 Starting NABCA multi-entity extraction...")

        # Initialize clients
        import os
        import boto3
        from supabase import create_client

        supabase = create_client(
            os.getenv("NEXT_PUBLIC_SUPABASE_URL"),
            os.getenv("SUPABASE_SERVICE_ROLE_KEY")
        )

        textract_client = boto3.client('textract', region_name=os.getenv("AWS_REGION", "us-east-1"))
        s3_client = boto3.client('s3', region_name=os.getenv("AWS_REGION", "us-east-1"))

        # Fetch PDF artifacts
        source_ids = ["cc74c14b-f43c-4b76-8c2d-b78f901989bb"]
        query = supabase.table("artifacts").select("*").eq("artifact_type", "pdf")
        if source_ids:
            query = query.in_("source_id", source_ids)

        artifacts_response = query.execute()
        artifacts = artifacts_response.data

        context.log.info(f"📄 Found {len(artifacts)} PDF artifacts to process")

        # Table identification patterns (from template)
        table_patterns = [
        {
                "tableName": "Brand Leaders",
                "entityName": "raw_nabca_table_1",
                "maxColumns": 12,
                "minColumns": 8,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "brand",
                                "type": "TEXT",
                                "label": "Brand",
                                "description": "The name of the spirit brand",
                                "classification": "Master Data"
                        },
                        {
                                "name": "type",
                                "type": "TEXT",
                                "label": "Type",
                                "description": "Spirit type/category (same as class)",
                                "classification": "Reference Data"
                        },
                        {
                                "name": "ytd_rank",
                                "type": "NUMBER",
                                "label": "Year to Date Case Sales Rank",
                                "description": "Rank of the brand based on case sales for YTD period",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "ytd_pct_total",
                                "type": "NUMBER",
                                "label": "Year to Date % Total",
                                "description": "Brand share (%) of total case sales YTD",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "ytd_case_sales",
                                "type": "NUMBER",
                                "label": "Year to Date Case Sales",
                                "description": "Total number of 9-liter cases sold YTD",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_vs_last_year",
                                "type": "NUMBER",
                                "label": "YTD +/- Last Year",
                                "description": "Difference in case sales vs same YTD period prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_case_sales",
                                "type": "NUMBER",
                                "label": "Current Month Case Sales",
                                "description": "Total 9L cases sold in current month",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_vs_last_year",
                                "type": "NUMBER",
                                "label": "Current Month +/- Last Year",
                                "description": "Difference vs same month last year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_case_sales",
                                "type": "NUMBER",
                                "label": "Last Twelve Months Case Sales",
                                "description": "Rolling 12-month total of 9L case sales",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 1,
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "% Total",
                        "+ or Last Year",
                        "Case Sales Last Twelve Months"
                ],
                "requiredHeaders": [
                        "BRAND",
                        "Type",
                        "Rank",
                        "Case Sales"
                ]
        },
        {
                "tableName": "Current Month Sales",
                "entityName": "raw_nabca_table_2",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "class",
                                "type": "TEXT",
                                "label": "Class",
                                "description": "The spirit class/category",
                                "classification": "Reference Data"
                        },
                        {
                                "name": "pct_total_dist_spirits",
                                "type": "NUMBER",
                                "label": "% Total Dist. Spirits",
                                "description": "Percentage of this class out of all distilled spirits sales",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "pct_of_class",
                                "type": "NUMBER",
                                "label": "% of Class",
                                "description": "Share of this class relative to its parent grouping",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "total_cases",
                                "type": "NUMBER",
                                "label": "Total Cases",
                                "description": "Total 9L cases sold for this class (all bottle sizes)",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_75l",
                                "type": "NUMBER",
                                "label": "1.75 L",
                                "description": "Cases sold in 1.75L bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_0l",
                                "type": "NUMBER",
                                "label": "1.0 L",
                                "description": "Cases sold in 1.0L bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml",
                                "type": "NUMBER",
                                "label": "750 ml",
                                "description": "Cases sold in 750ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml_traveler",
                                "type": "NUMBER",
                                "label": "750 ml Traveler",
                                "description": "Cases sold in 750ml traveler bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_375ml",
                                "type": "NUMBER",
                                "label": "375 ml",
                                "description": "Cases sold in 375ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_200ml",
                                "type": "NUMBER",
                                "label": "200 ml",
                                "description": "Cases sold in 200ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_100ml",
                                "type": "NUMBER",
                                "label": "100 ml",
                                "description": "Cases sold in 100ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_50ml",
                                "type": "NUMBER",
                                "label": "50 ml",
                                "description": "Cases sold in 50ml bottles",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 2,
                "titleKeywords": [
                        "CURRENT MONTH",
                        "TOTAL CASE SALES"
                ],
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "1.75 L",
                        "1.0 L",
                        "750 ml",
                        "375 ml",
                        "200 ml",
                        "100 ml",
                        "50 ml"
                ],
                "requiredHeaders": [
                        "CLASS",
                        "Dist. Spirits",
                        "Cases"
                ]
        },
        {
                "tableName": "YTD Sales",
                "entityName": "raw_nabca_table_3",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "class",
                                "type": "TEXT",
                                "label": "Class",
                                "description": "Spirit class/category",
                                "classification": "Reference Data"
                        },
                        {
                                "name": "pct_total_dist_spirits",
                                "type": "NUMBER",
                                "label": "% Total Dist. Spirits",
                                "description": "Class share (%) of all distilled spirits for YTD",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "pct_of_class",
                                "type": "NUMBER",
                                "label": "% of Class",
                                "description": "Share within the parent grouping",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "total_cases",
                                "type": "NUMBER",
                                "label": "Total Cases",
                                "description": "Total 9L cases for the class (all bottle sizes)",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_75l",
                                "type": "NUMBER",
                                "label": "1.75 L",
                                "description": "9L cases sold in 1.75L",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_0l",
                                "type": "NUMBER",
                                "label": "1.0 L",
                                "description": "9L cases sold in 1.0L",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml",
                                "type": "NUMBER",
                                "label": "750 ml",
                                "description": "9L cases sold in 750ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml_traveler",
                                "type": "NUMBER",
                                "label": "750 ml Traveler",
                                "description": "9L cases sold in 750ml traveler",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_375ml",
                                "type": "NUMBER",
                                "label": "375 ml",
                                "description": "9L cases sold in 375ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_200ml",
                                "type": "NUMBER",
                                "label": "200 ml",
                                "description": "9L cases sold in 200ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_100ml",
                                "type": "NUMBER",
                                "label": "100 ml",
                                "description": "9L cases sold in 100ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_50ml",
                                "type": "NUMBER",
                                "label": "50 ml",
                                "description": "9L cases sold in 50ml",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 3,
                "titleKeywords": [
                        "YEAR TO DATE",
                        "TOTAL CASE SALES"
                ],
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "1.75 L",
                        "1.0 L",
                        "750 ml",
                        "375 ml",
                        "200 ml",
                        "100 ml",
                        "50 ml"
                ],
                "requiredHeaders": [
                        "CLASS",
                        "Dist. Spirits",
                        "Cases"
                ]
        },
        {
                "tableName": "Rolling 12-Month Sales",
                "entityName": "raw_nabca_table_4",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "class",
                                "type": "TEXT",
                                "label": "Class",
                                "description": "Spirit class/category",
                                "classification": "Reference Data"
                        },
                        {
                                "name": "pct_total_dist_spirits",
                                "type": "NUMBER",
                                "label": "% Total Dist. Spirits",
                                "description": "Class share (%) of all distilled spirits for L12M",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "pct_of_class",
                                "type": "NUMBER",
                                "label": "% of Class",
                                "description": "Share within the parent grouping",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "total_cases",
                                "type": "NUMBER",
                                "label": "Total Cases",
                                "description": "Total 9L cases for the class (all bottle sizes)",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_75l",
                                "type": "NUMBER",
                                "label": "1.75 L",
                                "description": "9L cases sold in 1.75L",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_1_0l",
                                "type": "NUMBER",
                                "label": "1.0 L",
                                "description": "9L cases sold in 1.0L",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml",
                                "type": "NUMBER",
                                "label": "750 ml",
                                "description": "9L cases sold in 750ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_750ml_traveler",
                                "type": "NUMBER",
                                "label": "750 ml Traveler",
                                "description": "9L cases sold in 750ml traveler",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_375ml",
                                "type": "NUMBER",
                                "label": "375 ml",
                                "description": "9L cases sold in 375ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_200ml",
                                "type": "NUMBER",
                                "label": "200 ml",
                                "description": "9L cases sold in 200ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_100ml",
                                "type": "NUMBER",
                                "label": "100 ml",
                                "description": "9L cases sold in 100ml",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "bottle_50ml",
                                "type": "NUMBER",
                                "label": "50 ml",
                                "description": "9L cases sold in 50ml",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 4,
                "titleKeywords": [
                        "ROLLING 12 MONTH",
                        "CASE SALES"
                ],
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "1.75 L",
                        "1.0 L",
                        "750 ml",
                        "375 ml",
                        "200 ml",
                        "100 ml",
                        "50 ml"
                ],
                "requiredHeaders": [
                        "CLASS",
                        "Dist. Spirits",
                        "Cases"
                ]
        },
        {
                "tableName": "Brand Summary",
                "entityName": "raw_nabca_table_5",
                "maxColumns": 20,
                "minColumns": 12,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "class_brand",
                                "type": "TEXT",
                                "label": "Class & Brand",
                                "description": "Combined class/type and brand name (merged cell in PDF)",
                                "classification": "Master Data"
                        },
                        {
                                "name": "vendor",
                                "type": "TEXT",
                                "label": "Vendor",
                                "description": "The supplier or producer associated with the brand",
                                "classification": "Master Data"
                        },
                        {
                                "name": "case_sales_l12m",
                                "type": "NUMBER",
                                "label": "Case Sales Last Twelve Months",
                                "description": "Total cases sold in last rolling 12 months",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "case_sales_last_ytd",
                                "type": "NUMBER",
                                "label": "Case Sales Last Year to Date",
                                "description": "Total cases sold in same YTD period last year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_pct_of_type",
                                "type": "NUMBER",
                                "label": "This Year to Date % of Type",
                                "description": "Brand % share of its spirit type",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "ytd_case_sales",
                                "type": "NUMBER",
                                "label": "This Year to Date Case Sales",
                                "description": "Current YTD total case sales",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_case_sales",
                                "type": "NUMBER",
                                "label": "Case Sales Current Month",
                                "description": "Total case sales in current month",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_1_75l",
                                "type": "NUMBER",
                                "label": "Current Month 1.75 L",
                                "description": "Current month sales in 1.75L bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_1_0l",
                                "type": "NUMBER",
                                "label": "Current Month 1.0 L",
                                "description": "Current month sales in 1.0L bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_750ml",
                                "type": "NUMBER",
                                "label": "Current Month 750 ml",
                                "description": "Current month sales in 750ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_750ml_traveler",
                                "type": "NUMBER",
                                "label": "Current Month 750 ml Traveler",
                                "description": "Current month sales in 750ml traveler bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_375ml",
                                "type": "NUMBER",
                                "label": "Current Month 375 ml",
                                "description": "Current month sales in 375ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_200ml",
                                "type": "NUMBER",
                                "label": "Current Month 200 ml",
                                "description": "Current month sales in 200ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_100ml",
                                "type": "NUMBER",
                                "label": "Current Month 100 ml",
                                "description": "Current month sales in 100ml bottles",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_50ml",
                                "type": "NUMBER",
                                "label": "Current Month 50 ml",
                                "description": "Current month sales in 50ml bottles",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 5,
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "L12M",
                        "YTD",
                        "% of Type",
                        "Current Month"
                ],
                "requiredHeaders": [
                        "Class & Type",
                        "Brand",
                        "Vendor",
                        "Case Sales"
                ]
        },
        {
                "tableName": "Vendor Top 100",
                "entityName": "raw_nabca_table_6",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "vendor",
                                "type": "TEXT",
                                "label": "Vendor",
                                "description": "The supplier or producer",
                                "classification": "Master Data"
                        },
                        {
                                "name": "rank",
                                "type": "NUMBER",
                                "label": "Rank",
                                "description": "Position of vendor based on sales performance",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "share_of_market",
                                "type": "NUMBER",
                                "label": "Share of Market",
                                "description": "Vendor percentage share of overall spirits market",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "l12m_this_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months This Year",
                                "description": "Total case sales for last 12 months",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_prior_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months Prior Year",
                                "description": "Total case sales for same 12-month period in previous year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_change",
                                "type": "NUMBER",
                                "label": "+/- (Last 12 Months)",
                                "description": "Difference in sales between this year and last year L12M",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_this_year",
                                "type": "NUMBER",
                                "label": "This Year to Date",
                                "description": "Total case sales YTD for current year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_last_year",
                                "type": "NUMBER",
                                "label": "Last Year to Date",
                                "description": "Total case sales YTD for prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_change",
                                "type": "NUMBER",
                                "label": "+/- (YTD)",
                                "description": "Difference in sales between this YTD and last YTD",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_this_year",
                                "type": "NUMBER",
                                "label": "Current Month This Year",
                                "description": "Total case sales for current month",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_last_year",
                                "type": "NUMBER",
                                "label": "Current Month Last Year",
                                "description": "Total case sales for same month last year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_change",
                                "type": "NUMBER",
                                "label": "+/- (Current Month)",
                                "description": "Difference in sales between this month and same month last year",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 6,
                "titleKeywords": [
                        "TOP 100",
                        "VENDORS"
                ],
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "Last 12 Months Prior Year",
                        "This Year to Date",
                        "Current Month"
                ],
                "requiredHeaders": [
                        "Vendor",
                        "Rank",
                        "Share of Market",
                        "Last 12 Months This Year"
                ]
        },
        {
                "tableName": "Vendor Top 20 by Class",
                "entityName": "raw_nabca_table_7",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "class_vendor",
                                "type": "TEXT",
                                "label": "Class / Vendor",
                                "description": "Combined class and vendor name (merged cell in PDF)",
                                "classification": "Master Data"
                        },
                        {
                                "name": "rank",
                                "type": "NUMBER",
                                "label": "Rank",
                                "description": "Position of vendor within the class based on sales",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "share_of_market",
                                "type": "NUMBER",
                                "label": "Share of Market",
                                "description": "Percentage share of the class total sales for vendor",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "l12m_this_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months This Year",
                                "description": "Case sales for last 12 months (current year)",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_prior_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months Prior Year",
                                "description": "Case sales for same 12-month period in prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_change",
                                "type": "NUMBER",
                                "label": "+/- (Last 12 Months)",
                                "description": "Difference in sales between this year and last year L12M",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_this_year",
                                "type": "NUMBER",
                                "label": "This Year to Date",
                                "description": "Case sales YTD for current year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_last_year",
                                "type": "NUMBER",
                                "label": "Last Year to Date",
                                "description": "Case sales YTD for prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_change",
                                "type": "NUMBER",
                                "label": "+/- (YTD)",
                                "description": "Difference in sales between this YTD and last YTD",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_this_year",
                                "type": "NUMBER",
                                "label": "Current Month This Year",
                                "description": "Case sales for current month",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_last_year",
                                "type": "NUMBER",
                                "label": "Current Month Last Year",
                                "description": "Case sales for same month in prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_change",
                                "type": "NUMBER",
                                "label": "+/- (Current Month)",
                                "description": "Difference in sales between this month and same month last year",
                                "classification": "Fact Data"
                        }
                ],
                "tableNumber": 7,
                "titleKeywords": [
                        "TOP 20",
                        "VENDORS",
                        "BY CLASS"
                ],
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "Last 12 Months Prior Year",
                        "This Year to Date",
                        "Current Month"
                ],
                "requiredHeaders": [
                        "Class / Vendor",
                        "Rank",
                        "Share of Market",
                        "Last 12 Months This Year"
                ]
        },
        {
                "tableName": "Control States",
                "entityName": "raw_nabca_table_8",
                "maxColumns": 15,
                "minColumns": 10,
                "fieldSchema": [
                        {
                                "name": "report_month",
                                "type": "TEXT",
                                "label": "Report Month",
                                "description": "Month of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "report_year",
                                "type": "TEXT",
                                "label": "Report Year",
                                "description": "Year of the report (extracted from filename)",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "vendor_brand",
                                "type": "TEXT",
                                "label": "Vendor / Brand",
                                "description": "Combined vendor and brand name (merged cell in PDF)",
                                "classification": "Master Data"
                        },
                        {
                                "name": "class",
                                "type": "TEXT",
                                "label": "Class",
                                "description": "Spirit class/category associated with the brand",
                                "classification": "Reference Data"
                        },
                        {
                                "name": "l12m_this_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months This Year",
                                "description": "Case sales for last 12 months (current year)",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_prior_year",
                                "type": "NUMBER",
                                "label": "Last 12 Months Prior Year",
                                "description": "Case sales for same 12-month period in prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "l12m_pct_change",
                                "type": "NUMBER",
                                "label": "% Change (Last 12 Months)",
                                "description": "Percentage change in sales between this year and last year L12M",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "ytd_this_year",
                                "type": "NUMBER",
                                "label": "This Year to Date",
                                "description": "Case sales YTD for current year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_last_year",
                                "type": "NUMBER",
                                "label": "Last Year to Date",
                                "description": "Case sales YTD for prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "ytd_pct_change",
                                "type": "NUMBER",
                                "label": "% Change (YTD)",
                                "description": "Percentage change in sales between this YTD and last YTD",
                                "classification": "Dimensional Data"
                        },
                        {
                                "name": "current_month_this_year",
                                "type": "NUMBER",
                                "label": "Current Month This Year",
                                "description": "Case sales for current month",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_last_year",
                                "type": "NUMBER",
                                "label": "Current Month Last Year",
                                "description": "Case sales for same month in prior year",
                                "classification": "Fact Data"
                        },
                        {
                                "name": "current_month_pct_change",
                                "type": "NUMBER",
                                "label": "% Change (Current Month)",
                                "description": "Percentage change in sales between this month and same month last year",
                                "classification": "Dimensional Data"
                        }
                ],
                "tableNumber": 8,
                "fuzzyThreshold": 0.75,
                "optionalHeaders": [
                        "Last 12 Months Prior Year",
                        "% Change",
                        "Current Month This Year",
                        "Current Month Last Year"
                ],
                "requiredHeaders": [
                        "Vendor / Brand",
                        "Class",
                        "Last 12 Months This Year",
                        "This Year to Date"
                ]
        }
]

        # Target entities (8 NABCA tables)
        target_entities = ["raw_nabca_table_1","raw_nabca_table_2","raw_nabca_table_3","raw_nabca_table_4","raw_nabca_table_5","raw_nabca_table_6","raw_nabca_table_7","raw_nabca_table_8"]

        context.log.info(f"🎯 Target entities: {len(target_entities)} tables")
        context.log.info(f"📋 Table patterns configured: {len(table_patterns)}")

        # Process each PDF
        all_entity_records = {entity_name: [] for entity_name in target_entities}
        failed_artifacts = 0

        for artifact in artifacts:
            try:
                context.log.info(f"\n{'='*60}")
                context.log.info(f"📄 Processing artifact: {artifact['id']}")
                context.log.info(f"   Filename: {artifact.get('original_filename', 'unknown')}")

                # Parse report month/year from filename (format: 631_9L_1224.PDF)
                filename = artifact.get("original_filename", "")
                report_month, report_year = parse_report_date_from_filename(filename)

                if report_month and report_year:
                    context.log.info(f"📅 Parsed date: {report_month} {report_year}")
                else:
                    context.log.warning(f"⚠️  Could not parse date from: {filename}")

                # Check if artifact is already in S3
                artifact_metadata = artifact.get("metadata", {})
                if artifact_metadata.get("s3_bucket") and artifact_metadata.get("s3_key"):
                    # Artifact already in S3 - use existing location
                    s3_bucket = artifact_metadata["s3_bucket"]
                    s3_key = artifact_metadata["s3_key"]
                    context.log.info(f"✅ Using existing S3 location: s3://{s3_bucket}/{s3_key}")
                else:
                    # Artifact in Supabase storage - need to download and upload to S3
                    context.log.info("📥 Downloading from Supabase storage...")
                    pdf_data = get_artifact_pdf(supabase, s3_client, artifact, context)
                    if not pdf_data:
                        context.log.error(f"❌ Failed to retrieve PDF for {artifact['id']}")
                        failed_artifacts += 1
                        continue

                    # Upload to S3 for Textract
                    s3_bucket = os.getenv("TEXTRACT_S3_BUCKET") or os.getenv("AWS_S3_BUCKET")
                    s3_key = f"textract-temp/nabca-multi/{artifact['id']}/full.pdf"

                    context.log.info(f"☁️  Uploading to S3: s3://{s3_bucket}/{s3_key}")
                    s3_client.put_object(Bucket=s3_bucket, Key=s3_key, Body=pdf_data)

                # Start async Textract analysis (entire PDF)
                context.log.info("🔍 Starting Textract async analysis...")
                textract_response = textract_client.start_document_analysis(
                    DocumentLocation={'S3Object': {'Bucket': s3_bucket, 'Name': s3_key}},
                    FeatureTypes=['TABLES']
                )

                job_id = textract_response['JobId']
                context.log.info(f"⏳ Textract job ID: {job_id}")

                # Poll for completion (with extended timeout for large PDFs)
                import time
                max_wait = 7200  # 2 hours for large PDFs (718 pages)
                wait_interval = 10
                elapsed = 0

                while elapsed < max_wait:
                    time.sleep(wait_interval)
                    elapsed += wait_interval

                    status_response = textract_client.get_document_analysis(JobId=job_id)
                    status = status_response['JobStatus']

                    if status == 'SUCCEEDED':
                        context.log.info(f"✅ Textract completed after {elapsed}s ({elapsed/60:.1f} min)")
                        break
                    elif status == 'FAILED':
                        raise Exception(f"Textract job failed: {status_response.get('StatusMessage')}")

                    if elapsed % 60 == 0:
                        context.log.info(f"⏳ Textract still running... ({elapsed}s / {elapsed/60:.1f} min)")

                if status != 'SUCCEEDED':
                    raise Exception(f"Textract job timed out after {max_wait}s")

                # Collect ALL blocks from all pages
                context.log.info("📦 Retrieving Textract blocks...")
                all_blocks = status_response.get('Blocks', [])
                next_token = status_response.get('NextToken')
                page_count = 1

                while next_token:
                    response = textract_client.get_document_analysis(JobId=job_id, NextToken=next_token)
                    all_blocks.extend(response.get('Blocks', []))
                    next_token = response.get('NextToken')
                    page_count += 1
                    if page_count % 10 == 0:
                        context.log.info(f"   Retrieved {page_count} pages of blocks...")

                context.log.info(f"✅ Retrieved {len(all_blocks)} total blocks from {page_count} result pages")

                # Parse tables
                tables = parse_textract_tables(all_blocks)
                context.log.info(f"📊 Detected {len(tables)} tables in PDF")

                # Track assigned entities for sequential matching (tables with identical headers)
                assigned_entities = set()

                # Identify and extract data from each table
                for table_idx, table in enumerate(tables):
                    table_data = table.get('data', [])
                    page_number = table.get('page', 0)

                    if len(table_data) < 2:
                        context.log.debug(f"Skipping table {table_idx + 1} (too small: {len(table_data)} rows)")
                        continue

                    # Identify which NABCA table this is (with title-based and page-based matching)
                    identified_pattern = identify_nabca_table(table_data, table_patterns, assigned_entities, page_number, all_blocks, context)

                    if not identified_pattern:
                        context.log.debug(f"Table {table_idx + 1} (page {page_number}): Could not identify (skipping)")
                        continue

                    entity_name = identified_pattern['entityName']
                    table_name = identified_pattern['tableName']

                    # Track assigned entity for sequential matching
                    assigned_entities.add(entity_name)
                    confidence = identified_pattern.get('confidence', 0)

                    context.log.info(f"✅ Table {table_idx + 1} (page {page_number}): Identified as '{table_name}' → {entity_name} (confidence: {confidence:.2f})")

                    # Extract data using pattern
                    records = extract_table_data_multi_entity(
                        table_data,
                        identified_pattern,
                        report_month,
                        report_year,
                        artifact,
                        context
                    )

                    all_entity_records[entity_name].extend(records)
                    context.log.info(f"   → Extracted {len(records)} records for {entity_name}")

                context.log.info(f"✅ Completed artifact {artifact['id']}")

            except Exception as e:
                context.log.error(f"❌ Failed to process artifact {artifact['id']}: {str(e)}")
                context.log.error(traceback.format_exc())
                failed_artifacts += 1
                continue

        # Load data into all 8 tables
        context.log.info(f"\n{'='*60}")
        context.log.info("💾 Loading data into database tables...")

        load_summary = {}

        for entity_name, records in all_entity_records.items():
            if not records:
                context.log.info(f"  {entity_name}: No records to load")
                load_summary[entity_name] = {"loaded": 0, "failed": 0}
                continue

            context.log.info(f"  {entity_name}: Loading {len(records)} records...")

            # Batch insert
            loaded, failed = batch_insert_records(supabase, entity_name, records, context)
            load_summary[entity_name] = {"loaded": loaded, "failed": failed}

            context.log.info(f"    ✅ {loaded} loaded, ❌ {failed} failed")

        # Final summary
        total_loaded = sum(s["loaded"] for s in load_summary.values())
        total_failed = sum(s["failed"] for s in load_summary.values())

        context.log.info(f"\n{'='*60}")
        context.log.info(f"🎉 NABCA Multi-Entity Extraction Complete!")
        context.log.info(f"   Artifacts processed: {len(artifacts)} ({failed_artifacts} failed)")
        context.log.info(f"   Total records loaded: {total_loaded}")
        context.log.info(f"   Total records failed: {total_failed}")
        context.log.info(f"   Entities populated: {len([k for k, v in load_summary.items() if v['loaded'] > 0])}/8")

        return {
            "success": True,
            "artifacts_processed": len(artifacts),
            "artifacts_failed": failed_artifacts,
            "total_records_loaded": total_loaded,
            "total_records_failed": total_failed,
            "load_summary": load_summary,
        }

    except Exception as e:
        context.log.error(f"❌ NABCA multi-entity extraction failed: {str(e)}")
        context.log.error(traceback.format_exc())
        raise


def get_artifact_pdf(supabase, s3_client, artifact: Dict[str, Any], context) -> bytes:
    """Retrieve PDF file data from S3 or Supabase storage."""
    try:
        # Check if artifact has S3 metadata
        if artifact.get("metadata", {}).get("s3_bucket") and artifact.get("metadata", {}).get("s3_key"):
            context.log.info(f"Downloading from S3: s3://{artifact['metadata']['s3_bucket']}/{artifact['metadata']['s3_key']}")
            response = s3_client.get_object(
                Bucket=artifact["metadata"]["s3_bucket"],
                Key=artifact["metadata"]["s3_key"]
            )
            return response['Body'].read()
        else:
            # Download from Supabase storage
            file_path = artifact.get("file_path")
            if not file_path:
                raise Exception("No file_path found in artifact")

            context.log.info(f"Downloading from Supabase storage: {file_path}")
            response = supabase.storage.from_("artifacts").download(file_path)
            return response

    except Exception as e:
        context.log.error(f"Failed to retrieve PDF: {str(e)}")
        return None


def parse_textract_tables(blocks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Parse Textract blocks into table structure with O(1) lookups. Includes page numbers for sequential matching."""
    tables = []

    # PERFORMANCE: Build block ID lookup map once (O(n) instead of O(n²))
    block_map = {b['Id']: b for b in blocks if 'Id' in b}

    # Find all TABLE blocks
    table_blocks = [b for b in blocks if b.get('BlockType') == 'TABLE']

    for table_block in table_blocks:
        # Extract page number from table block
        page_number = table_block.get('Page', 0)

        # Find all CELL blocks for this table
        cell_blocks = []
        if 'Relationships' in table_block:
            for rel in table_block['Relationships']:
                if rel['Type'] == 'CHILD':
                    for cell_id in rel['Ids']:
                        cell_block = block_map.get(cell_id)  # O(1) lookup
                        if cell_block and cell_block.get('BlockType') == 'CELL':
                            cell_blocks.append(cell_block)

        # Build table grid
        if not cell_blocks:
            continue

        max_row = max(c.get('RowIndex', 0) for c in cell_blocks)
        max_col = max(c.get('ColumnIndex', 0) for c in cell_blocks)

        # Initialize grid
        grid = [['' for _ in range(max_col)] for _ in range(max_row)]

        # Fill grid
        for cell in cell_blocks:
            row = cell.get('RowIndex', 1) - 1  # Convert to 0-indexed
            col = cell.get('ColumnIndex', 1) - 1

            # Get cell text
            cell_text = ''
            if 'Relationships' in cell:
                for rel in cell['Relationships']:
                    if rel['Type'] == 'CHILD':
                        for word_id in rel['Ids']:
                            word_block = block_map.get(word_id)  # O(1) lookup
                            if word_block and word_block.get('BlockType') == 'WORD':
                                cell_text += word_block.get('Text', '') + ' '

            grid[row][col] = cell_text.strip()

        tables.append({'data': grid, 'page': page_number})

    return tables


def identify_nabca_table(table_data: List[List[str]], patterns: List[Dict], assigned_entities: set, page_number: int, all_blocks: List[Dict], context) -> Optional[Dict]:
    """
    Identify which NABCA table this is based on header matching and title keywords.
    Uses title-based disambiguation for patterns with identical headers (Tables 2-4, 6-7).
    Port of TypeScript identifyTable() function.

    Title-based sequential matching:
    - Table 2: "CURRENT MONTH" + "TOTAL CASE SALES"
    - Table 3: "YEAR TO DATE" + "TOTAL CASE SALES"
    - Table 4: "ROLLING 12 MONTH" + "CASE SALES"
    - Table 6: "TOP 100" + "VENDORS"
    - Table 7: "TOP 20" + "VENDORS" + "BY CLASS"
    """
    from difflib import SequenceMatcher

    # Extract LINE blocks for this page (for title matching)
    page_lines = []
    for block in all_blocks:
        if block.get('BlockType') == 'LINE' and block.get('Page') == page_number:
            line_text = block.get('Text', '').upper()
            page_lines.append(line_text)

    page_text = ' '.join(page_lines)
    context.log.debug(f"Page {page_number} text preview: {page_text[:200]}...")

    best_match = None
    best_score = 0.0

    for pattern in patterns:
        # Find header row (position-agnostic)
        header_row_idx = find_header_row(
            table_data,
            pattern['requiredHeaders'],
            pattern.get('fuzzyThreshold', 0.75)
        )

        if header_row_idx == -1:
            continue

        # Calculate base confidence score from header matching
        headers = table_data[header_row_idx]
        required_headers = pattern['requiredHeaders']

        matched_count = 0
        for required_header in required_headers:
            for header in headers:
                if not header:
                    continue

                similarity = SequenceMatcher(None, header.lower(), required_header.lower()).ratio()
                if similarity >= pattern.get('fuzzyThreshold', 0.75):
                    matched_count += 1
                    break

        score = matched_count / len(required_headers) if required_headers else 0

        # TITLE-BASED DISAMBIGUATION: Check if title keywords match
        title_keywords = pattern.get('titleKeywords', [])
        title_match_boost = 0.0

        if title_keywords:
            # Check if ALL title keywords are present in page text
            keywords_matched = sum(1 for keyword in title_keywords if keyword.upper() in page_text)
            if keywords_matched == len(title_keywords):
                # All keywords matched - strong boost to confidence
                title_match_boost = 0.3
                context.log.debug(f"   ✅ Title match for {pattern.get('entityName')}: all {len(title_keywords)} keywords found")
            elif keywords_matched > 0:
                # Partial match - smaller boost
                title_match_boost = 0.1 * (keywords_matched / len(title_keywords))
                context.log.debug(f"   ⚠️  Partial title match for {pattern.get('entityName')}: {keywords_matched}/{len(title_keywords)} keywords")

        # Apply title match boost
        final_score = score + title_match_boost

        if final_score > best_score:
            best_score = final_score
            best_match = {
                **pattern,
                'confidence': final_score,
                'headerRowIndex': header_row_idx,
                'titleMatchBoost': title_match_boost,
            }

    # Only return if confidence is above threshold
    if best_match and best_match['confidence'] >= 0.6:
        return best_match

    return None


def find_header_row(table_data: List[List[str]], required_headers: List[str], fuzzy_threshold: float) -> int:
    """
    Find the row that contains the headers (position-agnostic).
    Port of TypeScript findHeaderRow() function.
    """
    from difflib import SequenceMatcher

    for row_idx, row in enumerate(table_data[:10]):  # Check first 10 rows only
        matched_count = 0

        for required_header in required_headers:
            for cell in row:
                if not cell:
                    continue

                similarity = SequenceMatcher(None, cell.lower(), required_header.lower()).ratio()
                if similarity >= fuzzy_threshold:
                    matched_count += 1
                    break

        # If we matched most required headers, this is the header row
        if matched_count >= len(required_headers) * 0.7:  # 70% threshold
            return row_idx

    return -1  # Not found


def clean_cell_value(value: Any, field_name: str, field_type: str, context) -> Any:
    """
    Clean cell values to handle Textract OCR quality issues.

    Common issues:
    - Space-separated values: "1 1", "49 49" -> Extract first number
    - Text in numeric fields: "VISA", "NON" -> Return None
    - Malformed decimals: ".00 .00", ":00" -> Return None
    """
    import re

    if value is None or (isinstance(value, str) and not value.strip()):
        return None

    value_str = str(value).strip()

    # For NUMBER type fields, apply numeric cleaning
    if field_type == 'NUMBER':
        # Check if value contains spaces (likely merged cells)
        if ' ' in value_str:
            # Extract first valid number
            parts = value_str.split()
            for part in parts:
                # Try to extract numeric value
                match = re.match(r'^-?\d+\.?\d*$', part.replace(',', ''))
                if match:
                    cleaned = part.replace(',', '')
                    context.log.warning(f"⚠️  Cleaned space-separated value '{value_str}' -> '{cleaned}' for field '{field_name}'")
                    return cleaned

            # No valid number found
            context.log.warning(f"⚠️  Rejecting invalid numeric value '{value_str}' for field '{field_name}'")
            return None

        # Check if value is purely alphabetic (text in numeric field)
        if re.match(r'^[A-Za-z]+$', value_str):
            context.log.warning(f"⚠️  Rejecting text value '{value_str}' in numeric field '{field_name}'")
            return None

        # Handle malformed decimals starting with . or :
        if value_str.startswith('.') or value_str.startswith(':'):
            # Try to fix common patterns
            if re.match(r'^\.[0-9]+$', value_str):  # .00, .25, etc.
                fixed_value = '0' + value_str
                context.log.warning(f"⚠️  Fixed malformed decimal '{value_str}' -> '{fixed_value}' for field '{field_name}'")
                return fixed_value
            else:
                # Can't fix - reject
                context.log.warning(f"⚠️  Rejecting malformed numeric value '{value_str}' for field '{field_name}'")
                return None

        # Valid numeric value - clean commas
        return value_str.replace(',', '')

    # For TEXT fields, return as-is
    return value_str


def extract_table_data_multi_entity(
    table_data: List[List[str]],
    pattern: Dict,
    report_month: Optional[str],
    report_year: Optional[str],
    artifact: Dict,
    context
) -> List[Dict[str, Any]]:
    """
    Extract data from table using identified pattern.
    """
    # Find header row dynamically using required headers
    required_headers = pattern.get('requiredHeaders', [])
    fuzzy_threshold = pattern.get('fuzzyThreshold', 0.75)

    header_row_idx = find_header_row(table_data, required_headers, fuzzy_threshold)
    if header_row_idx == -1:
        context.log.warning(f"Could not find header row for {pattern.get('tableName')}")
        return []

    headers = table_data[header_row_idx]
    data_rows = table_data[header_row_idx + 1:]

    context.log.debug(f"   Found header row at index {header_row_idx}: {headers[:5]}...")  # Log first 5 headers

    # Get field schema for POSITIONAL MAPPING (no fuzzy matching)
    field_schema = pattern.get('fieldSchema', [])

    # Count non-metadata fields (fields that actually appear in the table)
    data_fields = [f for f in field_schema if f['name'] not in ['report_month', 'report_year']]
    metadata_fields = [f for f in field_schema if f['name'] in ['report_month', 'report_year']]

    context.log.debug(f"   Using positional mapping: {len(data_fields)} data fields + {len(metadata_fields)} metadata fields = {len(field_schema)} total")

    # Extract records using POSITIONAL MAPPING (no fuzzy matching needed)
    records = []
    for row in data_rows:
        # Skip empty rows
        if all(not cell or not str(cell).strip() for cell in row):
            continue

        # Validate row length matches data fields (not including metadata)
        if len(row) != len(data_fields):
            context.log.warning(f"   Skipping row with mismatched column count: expected {len(data_fields)} data columns, got {len(row)}")
            continue

        # POSITIONAL MAPPING: Map data fields to row positions
        record = {}
        row_idx = 0  # Track position in the actual table row

        for field in field_schema:
            field_name = field['name']
            field_type = field.get('type', 'TEXT')

            # Skip metadata fields (populated separately)
            if field_name in ['report_month', 'report_year']:
                continue

            # Get value from table row at current position
            if row_idx < len(row):
                value = row[row_idx]

                # Apply Textract OCR cleaning
                cleaned_value = clean_cell_value(value, field_name, field_type, context)
                record[field_name] = cleaned_value

                row_idx += 1  # Move to next column in table

        # Add metadata
        if len(record) >= len(data_fields) * 0.4:  # At least 40% of data fields populated
            record['report_month'] = report_month
            record['report_year'] = report_year
            record['_artifact_id'] = artifact['id']
            record['_source_id'] = artifact.get('source_id')
            records.append(record)

    return records


def batch_insert_records(supabase, table_name: str, records: List[Dict], context) -> tuple:
    """Insert records in batches with error handling."""
    batch_size = 100
    loaded_count = 0
    failed_count = 0

    # Clean records (remove metadata fields starting with _)
    clean_records = []
    for record in records:
        clean_record = {k: v for k, v in record.items() if not k.startswith('_')}
        clean_records.append(clean_record)

    for i in range(0, len(clean_records), batch_size):
        batch = clean_records[i:i + batch_size]

        try:
            response = supabase.table(table_name).insert(batch).execute()
            loaded_count += len(batch)
        except Exception as e:
            context.log.error(f"Batch insert failed: {str(e)}")

            # Try one by one
            for record in batch:
                try:
                    supabase.table(table_name).insert(record).execute()
                    loaded_count += 1
                except Exception as record_error:
                    context.log.error(f"Failed to insert record: {str(record_error)}")
                    failed_count += 1

    return (loaded_count, failed_count)


# ============================================================================
# TRANSFORMATION ASSETS
# ============================================================================

# No transformation needed for INTERIM entities
# Data flows directly to downstream Reference/Master entities


# ============================================================================
# LOAD ASSETS
# ============================================================================

# No separate load assets needed for multi-entity templates
# Data loading is handled within the multi-entity extraction asset


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def validate_record(record: Dict[str, Any], required_fields: List[str]) -> bool:
    """Validate that all required fields are present and non-empty."""
    for field in required_fields:
        if field not in record or record[field] is None or record[field] == "":
            return False
    return True


def deduplicate_records(
    records: List[Dict[str, Any]],
    key_fields: List[str]
) -> List[Dict[str, Any]]:
    """Remove duplicate records based on key fields."""
    seen = set()
    unique_records = []

    for record in records:
        # Create a key from specified fields
        key = tuple(record.get(field) for field in key_fields)

        if key not in seen:
            seen.add(key)
            unique_records.append(record)

    return unique_records


def parse_date(value: Any) -> Optional[str]:
    """Parse various date formats to ISO format."""
    if not value:
        return None

    import dateutil.parser

    try:
        if isinstance(value, str):
            dt = dateutil.parser.parse(value)
            return dt.date().isoformat()
        return str(value)
    except Exception:
        return None


def parse_timestamp(value: Any) -> Optional[str]:
    """Parse various timestamp formats to ISO format."""
    if not value:
        return None

    import dateutil.parser

    try:
        if isinstance(value, str):
            dt = dateutil.parser.parse(value)
            return dt.isoformat()
        return str(value)
    except Exception:
        return None

