'use client';

/**
 * AI Extractor Component
 *
 * Allows users to extract structured data from artifacts using AI
 * Based on spec section 4, Flow 2: AI-Powered Extraction
 */

import { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Loader2, Sparkles, ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import type { Artifact } from '@/types/artifacts';
import { CorrectionTable, type CorrectionData } from '@/components/extraction/correction-table';
import { SaveTemplateDialog } from '@/components/extraction/save-template-dialog';

// Configure PDF.js worker
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

interface AIExtractorProps {
  artifact: Artifact;
}

interface ExtractionResult {
  success: boolean;
  data?: Record<string, any>[];
  fields?: string[];
  selectors?: any; // Extraction rules generated by AI
  usage?: {
    input_tokens: number;
    output_tokens: number;
    total_tokens: number;
    estimated_cost: string;
  };
  error?: string;
}

export function AIExtractor({ artifact }: AIExtractorProps) {
  const [instructions, setInstructions] = useState('');
  const [extracting, setExtracting] = useState(false);
  const [result, setResult] = useState<ExtractionResult | null>(null);
  const [numPages, setNumPages] = useState<number>(0);
  const [pageNumber, setPageNumber] = useState<number>(1);
  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [pendingCorrectionData, setPendingCorrectionData] = useState<CorrectionData | null>(null);

  const handleExtract = async () => {
    if (!instructions.trim()) {
      toast.error('Please provide extraction instructions');
      return;
    }

    if (!artifact.raw_content) {
      toast.error('Artifact content not extracted yet. Please extract content first.');
      return;
    }

    try {
      setExtracting(true);
      setResult(null);

      const response = await fetch('/api/ai-extract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          artifact_id: artifact.id,
          instructions: instructions.trim(),
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'AI extraction failed');
      }

      setResult(data);
      toast.success('Data extracted successfully!');
    } catch (error) {
      console.error('AI extraction error:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to extract data');
    } finally {
      setExtracting(false);
    }
  };

  const handleSaveTemplate = (correctionData: CorrectionData) => {
    // Store correction data and open dialog
    setPendingCorrectionData(correctionData);
    setSaveDialogOpen(true);
  };

  const handleConfirmSaveTemplate = async (templateName: string, templateDescription: string) => {
    if (!pendingCorrectionData) return;

    try {
      // Build field schema from extracted fields
      const fieldSchema = result?.fields?.map((fieldName) => ({
        name: fieldName,
        description: `${fieldName} field`,
        type: 'string' as const,
        required: true,
      })) || [];

      // Create template with corrections AND extraction rules
      const response = await fetch('/api/templates', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: templateName,
          description: templateDescription,
          prompt: instructions,
          fields: fieldSchema,
          status: 'DRAFT',
          selectors: result?.selectors || null, // AI-generated extraction rules!
          corrections: {
            corrections: pendingCorrectionData.corrections,
            originalData: pendingCorrectionData.originalData,
            correctedData: pendingCorrectionData.correctedData,
            statistics: pendingCorrectionData.statistics,
          },
          extraction_method: result?.selectors ? 'hybrid' : 'ai', // hybrid if we have rules
          artifact_type: artifact.artifact_type,
          sample_artifact_id: artifact.id,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to create template');
      }

      toast.success('Template saved successfully!', {
        description: `"${templateName}" can now be reused for similar documents. ${pendingCorrectionData.statistics.correctedFields} corrections captured for learning.`,
      });

      console.log('Template created:', data.template);

      // Clear pending data
      setPendingCorrectionData(null);
    } catch (error) {
      console.error('Error saving template:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to save template');
      throw error; // Re-throw so dialog knows save failed
    }
  };

  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
  };

  // Use API endpoint for PDF to handle authentication and access
  const pdfUrl = artifact.artifact_type === 'pdf'
    ? `/api/artifacts/${artifact.id}/download`
    : null;

  const fileUrl = artifact.metadata?.public_url;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-full">
      {/* Left Column - Document Preview (Full Height) */}
      <div className="flex flex-col h-full">
        <div className="mb-2 px-6">
          <h3 className="font-semibold text-gray-900">Document Preview</h3>
          <p className="text-sm text-gray-500">{artifact.original_filename}</p>
        </div>

        <div className="flex-1 px-6 pb-6">
          {artifact.artifact_type === 'pdf' && pdfUrl ? (
            <div className="h-full flex flex-col space-y-4">
              <div className="flex-1 border rounded-lg overflow-auto bg-gray-50 flex items-center justify-center">
                <Document
                  file={pdfUrl}
                  onLoadSuccess={onDocumentLoadSuccess}
                  loading={
                    <div className="flex items-center justify-center h-full">
                      <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
                    </div>
                  }
                  error={
                    <div className="flex items-center justify-center h-full">
                      <p className="text-red-600">Failed to load PDF</p>
                    </div>
                  }
                >
                  <Page
                    pageNumber={pageNumber}
                    renderTextLayer={true}
                    renderAnnotationLayer={true}
                    width={700}
                  />
                </Document>
              </div>

              {numPages > 1 && (
                <div className="flex items-center justify-between">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setPageNumber(Math.max(1, pageNumber - 1))}
                    disabled={pageNumber <= 1}
                  >
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Previous
                  </Button>
                  <span className="text-sm text-gray-600">
                    Page {pageNumber} of {numPages}
                  </span>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setPageNumber(Math.min(numPages, pageNumber + 1))}
                    disabled={pageNumber >= numPages}
                  >
                    Next
                    <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                </div>
              )}
            </div>
          ) : artifact.artifact_type === 'html' ? (
            <div className="h-full border rounded-lg overflow-hidden bg-white relative">
              <iframe
                src={`/api/artifacts/${artifact.id}/download`}
                className="w-full h-full border-0"
                sandbox="allow-same-origin allow-scripts allow-forms allow-popups"
                title="HTML Preview"
                onLoad={() => console.log('HTML iframe loaded')}
                onError={() => console.error('HTML iframe error')}
              />
            </div>
          ) : (
            <div className="flex items-center justify-center h-full border rounded-lg bg-gray-50">
              <p className="text-gray-500">Preview not available</p>
            </div>
          )}
        </div>
      </div>

      {/* Right Column - Extraction */}
      <div className="flex flex-col h-full px-6 pb-6 overflow-y-auto">
        {/* Instructions */}
        <div className="mb-4">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-purple-600" />
            AI Extraction Instructions
          </h3>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                What data do you want to extract?
              </label>
              <Textarea
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
                placeholder="Example: Extract all invoice line items with columns: description, quantity, unit price, and total amount. Each row should be a separate product or service."
                rows={6}
                className="resize-none"
              />
              <p className="text-xs text-gray-500 mt-2">
                Be specific about the fields you want and their format. The AI will analyze the document
                and extract structured data based on your instructions.
              </p>
            </div>

            <Button
              onClick={handleExtract}
              disabled={extracting || !instructions.trim()}
              className="w-full"
            >
              {extracting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Extracting with AI...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Extract with AI
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Results */}
        {result && result.success && (
          <>
            {/* Token Usage */}
            {result.usage && (
              <div className="bg-blue-50 border-blue-200 border rounded-lg p-4 mb-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-gray-600">Input Tokens</p>
                      <p className="font-semibold text-gray-900">
                        {result.usage.input_tokens.toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-gray-600">Output Tokens</p>
                      <p className="font-semibold text-gray-900">
                        {result.usage.output_tokens.toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-gray-600">Total Tokens</p>
                      <p className="font-semibold text-gray-900">
                        {result.usage.total_tokens.toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-gray-600">Estimated Cost</p>
                      <p className="font-semibold text-green-700">
                        ${result.usage.estimated_cost}
                      </p>
                    </div>
                  </div>
              </div>
            )}

            {/* Correction Table - Editable with tracking */}
            {result.data && result.data.length > 0 && result.fields ? (
              <CorrectionTable
                fields={result.fields}
                data={result.data}
                onSaveTemplate={handleSaveTemplate}
              />
            ) : (
              <div className="border rounded-lg p-8 text-center">
                <p className="text-gray-500">No data extracted</p>
              </div>
            )}
          </>
        )}

        {/* Error Display */}
        {result && !result.success && (
          <div className="bg-red-50 border-red-200 border rounded-lg p-4">
            <p className="text-red-900 font-medium mb-2">Extraction Failed</p>
            <p className="text-red-700 text-sm">{result.error}</p>
          </div>
        )}
      </div>

      {/* Save Template Dialog */}
      <SaveTemplateDialog
        open={saveDialogOpen}
        onOpenChange={setSaveDialogOpen}
        onSave={handleConfirmSaveTemplate}
        correctionStats={pendingCorrectionData?.statistics}
      />
    </div>
  );
}
